### ISSUE TITLE
OPENCV 4.0 (MSYS2/Windows)

### ISSUE THREAD

**Issue by sylale** [dtschump/gmic#101]
Bonjour,

MSYS2 est passé à OPENCV 4.0
J'ai des erreurs de compilation avec cette version (gmic cli).
Pouvez-vous tester une compilation sous Linux avec cette dernière version d'OPENCV.
Merci, bonne année 2019!

**Comment by jtojnar** [comment]
Why was this closed? I only see hundreds of commits named "." around April 2 and latest G'MIC version still does not seem to detect OpenCV 4.

**Comment by dtschump** [comment]
What are the error messages ? OpenCV4 won't install here on my VM. Hard to check.

**Comment by jtojnar** [comment]
It fails to find it:

```
-- Checking for module 'opencv'
--   No package 'opencv' found
```

since it checks for `opencv` rather than `opencv4`:

https://github.com/dtschump/gmic/blob/4754e71913000d82db08c8b33e152d1dd805d86a/CMakeLists.txt#L188

If I manually replace it

```patch
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -185,7 +185,7 @@ if(FFTW3_FOUND)
 endif()
 
 if(ENABLE_OPENCV)
-  pkg_check_modules(OPENCV opencv)
+  pkg_check_modules(OPENCV opencv4)
 endif()
 if(OPENCV_FOUND)
   set(CLI_COMPILE_FLAGS "${CLI_COMPILE_FLAGS} -Dcimg_use_opencv")
```

it seems to find it and builds without an issue:

```
-- Checking for module 'opencv4'
--   Found opencv4, version 4.3.0
```

**Comment by dtschump** [comment]
That is great. I'm a total noob with `cmake`. If someone wants to modify it so that it can check either for OpenCV<4 or >=4, I'd be more than happy :)

**Comment by jtojnar** [comment]
I could do that but I am a bit confused about the project structure. The cmake script just adds the opencv-related flags globally, instead of just to the target that needs them, so I am not sure what actually uses it and cannot be sure it actually works.

I tried decoupling the projects to make them individually buildable in https://github.com/c-koi/gmic-qt/pull/81 but it was too coupled – e.g. it expects `CImg.h` and `gmic_stdlib.h` in the project directory instead of using them from the system.

**Comment by dtschump** [comment]
AFAIK, The only file that requires OpenCV is the CLI tool `gmic` (compiled from `gmic.cpp`).
The G'MIC-Qt plug-in actually doesn't use it at all.

**Comment by dtschump** [comment]
To be more precise : the G'MIC-Qt plug-in compiles its own version of the G'MIC engine, with a set of dependencies that he can choose precisely. Rather then relying on a globally installed `libgmic.so` file whose dependencies would not fit the use of a plug-in for GIMP (e.g. having OpenCV dependencies would be useless for the plug-in).
G'MIC is a quite modular and flexible library, so it can actually be compiled with or without some features enabled (that come with more or less dependencies, depending on the options we choose when compiling it). That's why most of the G'MIC interfaces (CLI too, plug-in, ...) are recompiling the G'MIC engine with their desired requirements, to avoid having useless dependencies.
The CLI tool `gmic` enables almost all possible dependencies, while the plug-in enables only a few of them.

**Comment by jtojnar** [comment]
Linux distributions usually prefer having a single version of each library – if there already is libgmic with opencv support on top of the required features, we can use that, rather than building a second lighter libgmic that overlaps API-wise.

I have opened https://github.com/dtschump/gmic/pull/218, which modernizes the build script a bit. That should also make it easier to make Linux distributions happy in the future.

**Comment by dtschump** [comment]
Is it OK to close this issue then ?
