### ISSUE TITLE
G'Mic blank screen on Windows 10 (Krita 4.1 & GIMP 2.8)

### ISSUE THREAD

**Issue by Seraaron** [dtschump/gmic#121]
I can't seem to open G'mic at all. I fist encountered this issue month ago, mentioned the problem on issue #95 and found no solution there, and I still have this issue now too. Just to be sure, I tried reinstalling Krita, and reinstalling G'Mic, and I just tried installing it on GIMP too and it still doesn't open.

I get a blanks screen in my taskbar that I can't select. (Or rather, when I do select it nothing happens).

![krita_2019-02-28_12-14-41](https://user-images.githubusercontent.com/40521082/53565835-781c7a00-3b52-11e9-8336-2181ca89de07.png)

![2019-02-28_12-11-17](https://user-images.githubusercontent.com/40521082/53565667-f9274180-3b51-11e9-98a4-bc76a7bb78b7.png)

If I leave it for long enough then the blank window eventually loads, and I see a little preview of what it should look like

![opera_2019-02-28_12-15-57](https://user-images.githubusercontent.com/40521082/53565897-a306ce00-3b52-11e9-883a-a622c6fbaa44.png)

But it still doesn't do anything when I select it. I've even tried looking in all the corners of my desktop in case the window is tiny or in a corner somewhere, but to no avail.

And for point of reference. It used to work fine. Just one day it started doing this and I have no idea why. Please can anyone help?

**Comment by Seraaron** [comment]
Wow. Okay I think I fixed this then. Turns out it _was_ opening ok, and I guess it was just hidden somewhere on my screen. I just had to force the window to be fullscreen and then it starting working fine again. Weird.

I guess this is a non-issue then. But I'll keep the post here incase anyone else runs into the same problem (because I was searching for hours and found nothing)!

**Comment by ironforward** [comment]
since this issue comes up when i searched for "gmic gimp blank screen", I wanted to add what fixed it for me, I hovered over the g'mic preview and clicked "Maximize" which finally made the window show up and render properly
![maximize_gmic](https://user-images.githubusercontent.com/7257376/121485857-75419e00-c985-11eb-85bb-81908bacde36.png)
![maximize_gmic_2](https://user-images.githubusercontent.com/7257376/121485865-77a3f800-c985-11eb-9721-cc5dfd7d5ed1.png)
