### ISSUE TITLE
G'MIC settings problems "Lights and Shadows> Relief light"

### ISSUE THREAD

**Issue by Pocholo17** [dtschump/gmic#186]
Possible bug or at least an annoyance" 
Hi David
I recently downloaded and installed the latest G'MIC version 2.8.2. On the filter "Lights and Shadows> Relief light"  the setting's decimals are not showing completely. http://gimpchat.com/files/6266_Foto.jpg

Are you aware of this? Thank you in advanced.

**Comment by dtschump** [comment]
Thanks for reporting, we are currently working on a fix !

**Comment by Pocholo17** [comment]
Thank you for getting back to me, David!

**Comment by dtschump** [comment]
Hello @Pocholo17 .
I've just released new binary packages for G'MIC 2.8.3_pre, with a fix included.
Is it possible for you to get the installer here : https://gmic.eu/files/prerelease/ for your architecture/OS, install the plug-in and tell us if the fix is working for you ?
That would be really nice,

Thanks !

**Comment by Pocholo17** [comment]
You did it, David. It's fixed. Thank you very much! Keep up the good work.

**Comment by dtschump** [comment]
Good news! All credit actually goes to @c-koi, who figured out a way to fix it.
I close the issue then.
