### ISSUE TITLE
rgb2lch lch2rgb problem

### ISSUE THREAD

**Issue by karo11** [dtschump/gmic#213]
With this example, I have an interesting display effect

gmic \(200.5,200.5,200.5:c\) +rgb2lch. +lch2rgb. +a x

delivers on my Mac

<img width="766" alt="Bildschirmfoto 2020-05-14 um 10 53 22" src="https://user-images.githubusercontent.com/1217623/81914253-5a112d00-95d1-11ea-86ba-8fc185e59568.png">

The green patch should be black like the leftmost one!

**Comment by dtschump** [comment]
Not so surprising, because if you write the exact value, you have a small error on the green channel, and as the display is renormalized in [0,255], you get a pure green image:
~~~~
bug :
  (200.5,200.5,200.5:c)
  +rgb2lch.
  +lch2rgb.
  e {I}
~~~~
and:
~~~~
$ gmic bug q
[gmic]-0./ Start G'MIC interpreter.
[gmic]-3./bug/ 200.5,200.50003051757812,200.5
[gmic]-3./ Quit G'MIC interpreter.
~~~~

**Comment by karo11** [comment]
Thank you David. 

I think for rgb values I'll round them to overcome this effect. 

Interesting that just green deviates a bit after lch2rgb. I had that effect only applying my LCH featuring (erroneously) on BW images (kr_mean_lch 2).
