### ISSUE TITLE
2.9.1: Incorrect minimum CMake version

### ISSUE THREAD

**Issue by krop** [dtschump/gmic#229]
In gmic 2.9.1, the minimum CMake version required was raised to 3.9.4.

This is incorrect: Some changes made to cmake/FindCImg.cmake require CMake >= 3.13.

`target_link_options(CImg::CImg INTERFACE ${LINK_FLAGS})`

The line above also requires at least CMake > 3.10 since `CImg::CImg` is an imported target.

**Comment by krop** [comment]
More issues in this file:
The imported `CURL::libcurl` target requires CMake >= 3.12
`X11::X11` and `X11::Xext` require CMake >= 3.14
`JPEG::JPEG` requires CMake >= 3.12

**Comment by dtschump** [comment]
@jtojnar @saknopper @radhermit @AronRubin ?

**Comment by krop** [comment]
I applied https://build.opensuse.org/package/view_file/graphics/gmic/0001-Don-t-use-CMake-commands-not-available-in-CMake-3.9.patch?expand=1 in order to build the last release with the CMake version we have.

I would only require a minor change for the Windows build.

**Comment by saknopper** [comment]
I'm sorry, I have no interest in maintaining the cmake build if (large) changes are being made without informing me. I hereby resign from my cmake duties.

That being said, it should be safe to raise the minimum required version.

**Comment by dtschump** [comment]
I won't modify the `CMakeLists.txt` file myself. So any PR would be appreciated.

**Comment by jtojnar** [comment]
Sorry, @saknopper did not realize there was a CMake maintainer.

----

I would prefer bumping the minimum CMake version since 3.14 seems to be [widely available](https://repology.org/project/cmake/versions).

Of course if the Windows pipeline does not have new enough CMake, it might not work, but I would still prefer updating the pipeline, since switching back to non-targets would contradict the whole point of https://github.com/dtschump/gmic/pull/218

@krop How hard do you think updating it would be? Do you have the pipeline source anywhere, maybe I could lend a hand in updating it?

**Comment by krop** [comment]
>
> @krop How hard do you think updating it would be? Do you have the pipeline source anywhere, maybe I could lend a hand in updating it?

Not possible for openSUSE Leap 15.1 and it will be harder for Leap 15.2 when it's released.

Feel free to bump the minimum CMake version, I can maintain my patch in our repositories.

**Comment by AronRubin** [comment]
I am a bit overextended right now but I can help eventually.

**Comment by dtschump** [comment]
@krop , does https://github.com/dtschump/gmic/pull/230 solve your issue ?

**Comment by krop** [comment]
> @krop , does #230 solve your issue ?

For obvious reasons, no. It solves your issue, not mine.
