### ISSUE TITLE
G'MIC - Morph function

### ISSUE THREAD

**Issue by davco61383** [dtschump/gmic#248]
Hi!

I'm new to using GIMP (2.10.14) and the G'MIC plugin.  I want to setup morph.  I have two photos and go to the plugin (G'MIC-Qt).  When I hit "OK", I receive the following:

*** Error in ./fx_morph_interactive/x_morph/ *** Command 'check_display': No display available.

I'm working off of a Mac (Mojave).  Is this a known issue?  Is there a way to resolve it?  

Thanks.

David

![PastedGraphic-1](https://user-images.githubusercontent.com/69327955/89589123-0189ae80-d813-11ea-88ae-3a93dbe520de.png)

**Comment by dtschump** [comment]
The G'MIC-Qt plug-in on Mac does not support filters requiring display windows. There are only a few, but `Morph [interactive]` is one of these. Mostly, all fiters post-fixed by `[interactive]` won't work on Mac.

**Comment by davco61383** [comment]
With that in mind, is there any way to use the "morph" function when working off of a Mac or will I need to wait for a possible future update?

**Comment by dtschump** [comment]
To be more precise : 
- Interactive stuffs in G'MIC on a Unix-based OS use the X11 library to display windows and stuffs inside.
- MacOSX apparently provides a port of X11, but it seems to be quite hard to install.
- For this reason, G'MIC-Qt packagers on Mac decided to disable display capabilities for Mac, so that it stays easy to install (as no additional X11 installation is required).

From our side : 
- We don't own a Mac, and in any ways, we have no plans to write specific code in G'MIC for managing native display windows on MacOSX.
- So, the only way of getting this kind of interactive filters working on a Mac is to compile the G'MIC-Qt plug-in with the X11 support, which seems to be hard enough to be honest.
- Another solution could be to run G'MIC inside a Virtual Machine on MacOSX (e.g. Ubuntu).

**Comment by geoffroy981** [comment]
hie 
I have the same issue with pop os ( linux) 
If have the answer it could be very nice .
That a little bottle in de sea. 
thanks.
