### ISSUE TITLE
cmake support dropped?

### ISSUE THREAD

**Issue by HJarausch** [dtschump/gmic#30]
There isn't any resources/CMakeLists.txt anymore.
Has cmake support dropped?

**Comment by a17r** [comment]
See also: https://github.com/dtschump/gmic/pull/29

**Comment by stefantalpalaru** [comment]
> There isn't any resources/CMakeLists.txt anymore.

You can find it in my fork: https://github.com/stefantalpalaru/gmic

**Comment by a17r** [comment]
As it stands, I am not going to package this.

**Comment by stefantalpalaru** [comment]
> As it stands, I am not going to package this.

I did: https://github.com/stefantalpalaru/gentoo-overlay/tree/master/media-gfx/gmic

But the live ebuild is obviously susceptible to break any time and version bumps are going to be complicated with an upstream that is hostile to packagers.

**Comment by dtschump** [comment]
> an upstream that is hostile to packagers.

I'm not sure you realize you have been the hostile person at the first place.
I've nothing against packagers, but of course I won't take

**Comment by stefantalpalaru** [comment]
> I've nothing against packagers, but of course I won't limit myself on the G'MIC code to please packagers.

Limit? Buddy, you don't understand why we need a configuration phase for the build system. You don't understand why a packager might want to avoid enabling an optional library even if it is already installed on the system.

The sad thing is that you don't know how to organise your own software. You rejected my patch that left the default case intact and only introduced a new define to optionally exclude the library part of gmic.cpp at preprocessing time (in case we wanted to link it to the shared library) and you came up with your own convoluted solution that now, in the default - statically linked - case, needs to compile the same file (gmic.cpp) twice with and without your own define and then link these two objects together. How is that better?

The code is full of WTF moments. You keep everything in one big file that takes ages to compile, instead of splitting it in smaller files that can be compiled in parallel. I'm sure compile times bother you too, but you just accept them as a fact of life. Much like that hand written dumpster fire of a Makefile.

> I'm not sure you realize you have been the hostile person at the first place.

This is not hostility. This is the frustration one gets from trying and failing to explain to another adult why they shouldn't bend their left arm over their head to scratch their right ear.

**Comment by a17r** [comment]
Strong words are not helpful, we all want to make open source software available for the greater good, and that gets us nowhere. But 'not helpful' is also the term I would use to describe the attitude shown by upstream here.

Now, this wouldn't be the first package to be built with handcrafted Makefiles, but this is the year 2017. If you make a change that is possibly breaking `CMakeLists.txt`, and you don't know how to follow-up with it, then *by all means* raise an issue on github for someone to pick it up and make a pull request. Leave a note in the `CMakeLists.txt` that it is probably broken. *Don't* just drop it silently. Apparently it wasn't broken before, and knowing cmake it is a very easy fix.

Then, build system matter aside, adopting a package also means having to deal with any bugs that users are going to report against it, dealing with build and install issues between version bumps and dependency changes. Often that means diving into the git history and hunting down a breaking change. This is downright impossible here to the human eye.

Isolated commits and meaningful messages go a long way towards identifying bad changes, and in the end will benefit you in the way you are confronted with bug reports. Reports that will hopefully happen as a sign your software is more widely distributed. That aside, think of yourself months and years from now, and the giant mess any lookup into past changes you don't precisely remember the reason for anymore is going to be.

**Comment by dtschump** [comment]
> you don't understand why we need a configuration phase for the build system. You don't understand why a packager might want to avoid enabling an optional library even if it is already installed on the system.

I perfectly understand that, and that's why my latest changes allow this. Please re-read what I've already answered. The current state of the code in the repo allows you to compile G'MIC with a shared library.
I shouldn't have to repeat that.

> The sad thing is that you don't know how to organise your own software

That's your point of view. IMHO, I know what I'm doing with my own project. If you think you can do better, then do it. I always encouraged personal initiatives, so please fork the project as much as you want, and make something better.

> How is that better?

Better than your patch with no doubt. You introduced additional parameters that were not needed in the method of the `gmic` class. That was worse. It broke the `gmic` API. There are a bunch of other concerns I had to deal with though. My solution is cleaner IMHO and gives you the requested feature.

> The code is full of WTF moments. You keep everything in one big file that takes ages to compile, instead of splitting it in smaller files that can be compiled in parallel. I'm sure compile times bother you too, but you just accept them as a fact of life. Much like that hand written dumpster fire of a Makefile.

I'd be curious to see what better code organization you can achieve. There are lot of template subtleties which make me think you wouldn't succeed as easily as you claim. Please fork, and show the world how talented you are.

> This is not hostility. This is the frustration one gets from trying and failing to explain to another adult why they shouldn't bend their left arm over their head to scratch their right ear.

This was clearly hostile as someone else noticed. Please learn to be polite before doing anything else when trying to contact a developer. Don't think that the hour or so you spent on a source file absolutely deserves to be included in the project.

Again, if you really think I'm wrong and you can do it better. Please fork the project.
I do not owe you anything. I've just released the source file of this project for everybody, and I'm doing my best to make it evolving in the right way.

**Comment by a17r** [comment]
>Better than your patch with no doubt. You introduced additional parameters that were not needed in the method of the gmic class. That was worse. It broke the gmic API. There are a bunch of other concerns I had to deal with though. My solution is cleaner IMHO and gives you the requested feature.

That's what the PR review is for. Point out what you can not accept about the patch and request a different way.

**Comment by dtschump** [comment]
> That's what the PR review is for. Point out what you can not accept about the patch and request a different way.

I've done it in my own way (which I think is better). And the OP didn't seem to be friendly enough (that was clear after 2 posts) to incite me discuss a lot.

> Apparently it wasn't broken before, and knowing cmake it is a very easy fix. 

Perfect! so do not hesitate to fix it and I'll be happy to include it again in the repo. I don't want to have non-working stuffs in the current state of the repo, that's why I've removed it.

> Strong words are not helpful, we all want to make open source software available for the greater good, and that gets us nowhere. But 'not helpful' is also the term I would use to describe the attitude shown by upstream here.

Honestly, don't expect other kind of responses as a contributor with this kind of posts.

**Comment by stefantalpalaru** [comment]
>> you don't understand why we need a configuration phase for the build system. You don't understand why a packager might want to avoid enabling an optional library even if it is already installed on the system.

>I perfectly understand that, and that's why my latest changes allow this.

Let me help you with an example: use this Makefile and disable OpenEXR support even if it is already installed: https://github.com/dtschump/gmic/blob/188f57f12829ea8c7b31b18b8267de31bcd0c821/src/Makefile#L279

With the CMakeLists.txt you removed, it's a matter of:

```
rm -f CMakeCache.txt; cmake -DENABLE_OPENEXR=OFF && make -j8
```

> You introduced additional parameters that were not needed in the method of the gmic class. That was worse. It broke the gmic API.

No, adding parameters with default values at the end of C++ methods does not break the API, but I'll concede that your method of checking some string from the client side is better.

What I was arguing about is the other half of my patch - the one introducing a new define.

> I'd be curious to see what better code organization you can achieve. There are lot of template subtleties which make me think you wouldn't succeed as easily as you claim. Please fork, and show the world how talented you are.

I'm not falling for that. You break backwards compatibility weekly and you generate some components that, due to that, can usually only be generated by the previous version of your binary - all this to avoid installing extra files like the library written in an interpreted language.

You did this to yourself. At each and every point you made the worst possible decision for code maintainability, so now you have the build system download http://gmic.eu/gmic_stdlib.h because you would need a compiled CLI tool to generate it from gmic_stdlib.gmic. Oh, and you "decompress" the data structure in the header back to the data in the .gmic file inside the common part of the code.

And don't even get me started on how you need 13 lines of code to check if help was requested in a command line parameter. "dumpster fire" was me being nice. Not getting into your manually unrolled loops is me being extra nice.

What you have here is a nugget of an image manipulation DSL packaged in the worst possible way, with scotch tape and rusty wires, with spit, mud and cow dung. I know you're very enthusiastic and responsive to user requests, but you couldn't organise your way out of a paper bag.

> Don't think that the hour or so you spent on a source file absolutely deserves to be included in the project.

An hour or so? Buddy, I spent days crawling neck deep through your sewer of a code base. It was not fun and, to top it off, I had you to deal with afterwards.

>> Apparently it wasn't broken before, and knowing cmake it is a very easy fix.

>Perfect! so do not hesitate to fix it and I'll be happy to include it again in the repo.

I already fixed it, but you were too busy watching Care Bear cartoons to notice it.

**Comment by dtschump** [comment]
> I already fixed it, but you were too busy watching Care Bear cartoons to notice it.

I wonder why you are taking so much time trying to explain me how silly I am and how bad the project is.
Just ignore me and the project, and get a better life.
At least if you do so, I'll get a better life.

I'm sure they are plenty of other and better projects waiting for help from such an amazing and skilled contributor as you. Do not make them wait too long.

Goodbye.
