### ISSUE TITLE
Cli Only - fx_frame_fuzzy - Applies sepia tone on output to disk

### ISSUE THREAD

**Issue by RodneyEbanks** [dtschump/gmic#370]
The fx_frame_fuzzy filter applies a sepia tone effect to output image when saved (tested v3.0.2 & 3.0.3).

Effect is not applied to Display output and is not present in output from GIMP plugin nor standalone Windows QT interface.

C:\gmic_cli_win64\gmic-3.0.3_pre-cli-win64\gmic "image.jpg" fx_frame_fuzzy 3,3,3,1.8,30,30,255,255 -o "output.jpg"

**Comment by dtschump** [comment]
That is because the output of this command is a RGBA image, so a 4-channel image.
`.jpg` format allows 4-channels images, but this does not correspond to RGBA, but to CMYK, which means in your case there is a change of the meaning of the pixel values stored in your output file.
You can force the output of the filter to be RGB only (3-channels), before saving the `.jpg` file, with command `to_rgb` : 
~~~
C:\gmic_cli_win64\gmic-3.0.3_pre-cli-win64\gmic "image.jpg" fx_frame_fuzzy 3,3,3,1.8,30,30,255,255 -to_rgb -o "output.jpg"
~~~

**Comment by RodneyEbanks** [comment]
Sorry, for posting something I should have been able to research my way through.

Great program by the way.

Good luck with your NFTs, they are very interesting and unique.
