### ISSUE TITLE
gmic for gimp 2.10 LINUX !!!!

### ISSUE THREAD

**Issue by anim4k** [dtschump/gmic#48]
hey 
The developers thanked this very wonderful addition
Always use this add-on in my work but did not work with me on Linux Mint new version of the program gimp 2.10

**Comment by JohnVV** [comment]
builds and works just fine for me on OpenSUSE - tumbleweed 
git - pull Gimp
git - pull Gmic 

and using the "config.site"  build method in my home bin folder 
after adding the new gcc7 -Isystem include $PATH to the config.site file everything builds just fine 
---------  the line in the config.site ---- 
" export CPLUS_INCLUDE_PATH="/usr/include/c++/7" "

**Comment by ibqn** [comment]
How about 64bit build for windows?

**Comment by anim4k** [comment]
JohnVV thank you but not work 'errer' mint 18.3 xfce :/

**Comment by dtschump** [comment]
Right now, for Debian-based systems, I don't have a solution.
We need to wait a bit that GIMP 2.10 becomes available in the repositories, along with the 2.10 development files (headers and libraries) to be able to compile the G'MIC plug-in for GIMP 2.10.
On Linux, the plug-in for 2.8 should work anyway, and if it doesn't, you should try compiling it from sources (it's not that hard, follow the instructions here : http://gmic.eu/download.shtml#source).

**Comment by JohnVV** [comment]
did you build babl and gegl in the gimp build folder ?
along with png16 and install libmypaint-1.3.0 and mypaint-brushes-1.3.0
as in building the git pulls using the wiki build instructions 
https://wiki.gimp.org/wiki/Hacking:Building/Linux


PS. i have been building the source and dev code since 2001 

then there is a bit of a ERROR still in the make file about "gmic-qt" in the wrong folder ( up one to hight in the tree )

run make after exporting 

"export PREFIX=/PATH/TO/gimp-2.10.0"

and then sourcing the "config.site"

"source $PREFIX/share/config.site"

then "make gmic-qt " builds just fine

**Comment by kyrios123** [comment]
Looks like gimp 2.10 is [now available](https://sources.debian.org/src/gimp/) in Debian sid.

On Solus (linux x86_64), the v.2.2.2 tarball fails to build (logs [here](https://hastebin.com/ahelinuyek.swift)). The exact same tarball used to build fine with gimp 2.8.22.

**Comment by dtschump** [comment]
I'll probably try compiling G'MIC for GIMP 2.10 on Debian sid this afternoon.
If everything goes well, I'll be able to provide a binary from the G'MIC download page.

It's a bit difficult compiling the plug-in for GIMP 2.10 as long as the official repositories of the distro still sticks with GIMP 2.8. We have to wait they all make the transition officially to GIMP 2.10

**Comment by dtschump** [comment]
I've been able to compile the G'MIC-Qt plug-in for GIMP 2.10 on Linux (Debian Sid).
I've added the link on the [G'MIC download page](https://gmic.eu/download.shtml).
Let me know if that is working for you. It should probably work also for other Debian-based distros.
