### ISSUE TITLE
G'MIC won't open on MacOS

### ISSUE THREAD

**Issue by DarkKeys7** [dtschump/gmic#95]
<img width="530" alt="screen shot 2018-12-01 at 8 19 12 pm" src="https://user-images.githubusercontent.com/32288490/49335867-fcd71680-f5aa-11e8-9e63-68d3c8741aeb.png">

When I try to open G'MIC, the application icon will show up, but the GUI will not appear, and a right-click on the icon shows that it isn't responding. I'm running GIMP version 2.10.8 on MacOS Mojave, with G'MIC version 2.4.1 from the .tgz archive link. Any help would be greatly appreciated.
Thanks,
Brian

**Comment by Seraaron** [comment]
I have this same problem! But I'm on Windows 10 and using the app with Krita.

When I hover over the window that appears, it gives a preview of a blank white screen, but I can't interact with it or open it. Only force quit the window.

It's completely unusable. I'm using Krita version 4.1.1 now; but I had the same issue in 4.1.0 too. But I don't think it has anything to do with Krita because strangely it just started happening one day, and when I re-installed previous versions of Krita it still doesn't work.

Annoyingly, there's no error message or crash report either.

**Comment by monkeyghost** [comment]
Exact same problem here as @DarkKeys7. Installation is correct, fiters are visible in Gimp but once trying to access the GMIC filter, the interface doesn´t pop up. On a different Mac, the same process worked just fine. Trying to uninstall everything, clean the MacOS and reinstalling didn´t solve the issue. Unexplainable and can´t seem to find a solution.

Any ideas?

Versions used:
MacOS Mojave 10.14.2
GMIC 2.4.5
GIMP 2.10.8

**Comment by Seraaron** [comment]
@dtschump 
![2019-01-29_19-45-08](https://user-images.githubusercontent.com/40521082/51935712-671b0480-23fe-11e9-83ec-c3dd57a38ff1.png) I still have this issue. It's just a white box that I can't select when I try to open G'Mic. Do you have any idea what might be causing this? It seems to not be an isolated issue (and not just Mac OS related).

**Comment by dtschump** [comment]
I don't have a Mac so I can't help much, but maybe @karo11 could help ?

**Comment by karo11** [comment]
I don't see any problem. I am on 10.14.3 with Gimp 2.10.8 from gimp.org using gmic-qt from Andrea (wget -q -O - https://github.com/aferrero2707/gimp-plugins-collection/releases/download/continuous/GMIC-Gimp-2.10-OSX.tgz | tar -xC ~/Library/Application\ Support/GIMP/2.10/plug-ins/ - ; ls -l ~/Library/Application\ Support/GIMP/2.10/plug-ins/gmic_gimp_qt) latest version:
<img width="434" alt="bildschirmfoto 2019-01-30 um 09 10 40" src="https://user-images.githubusercontent.com/1217623/51967358-68384a00-246f-11e9-8027-04740fb7931e.png">

XQuartz installed? it's necessary!

**Comment by DarkKeys7** [comment]
Thank you, @karo11! I didn't have XQuartz installed, works fine now :)
